POST  http://localhost:3000/api/playerGames/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjcyNjQ5OTcsImV4cCI6MTcyNzI2ODU5N30.rEPdmun0Ei_ZpVYPxf59KfJSn99K3qnKa18IakQvj7k

{ 
    "playerId" : 350,
    "dice1Result": 4, 
    "dice2Result": 3, 
    "overallResult": "Win"
}