services:
  frontend:
    build:
      context: ./client
    image: node:20-alpine
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5050:5050"
    volumes:
      - ./server:/usr/src/app
      - ./data:/usr/src/app/data
    environment:
      - DATABASE_URL=/usr/src/app/data/dev.db

volumes:
  data:
    driver: local