services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - /usr/src/app/node_modules
      - ./db:/server/prisma/db
  
volumes:
  node_modules:
  data:
    driver: local